language: java
jdk: openjdk8
before_install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-linux-x86_64.zip
  - unzip protoc-3.7.0-linux-x86_64.zip -d ./
  - ls
  - sudo mv ./protoc-3.7.0-linux-x86_64/bin/protoc /usr/bin/
install: mvn clean package