language: java
jdk:
  - openjdk8
on:
    tags: true
    repo: tcpayDev/peppa-proto
before_install:
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.7.0/protoc-3.7.0-linux-x86_64.zip
  - unzip protoc-3.7.0-linux-x86_64.zip -d /tmp/
  - export PATH=/tmp/bin:$PATH
cache:
  directories:
    - /home/travis/.m2/
install:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: releases
  user: "tcpayDev"
  password: "Chenyu123!@#"
  file: target/release.jar
  skip_cleanup: true
  on:
    tags: true
    repo: tcpayDev/peppa-proto