name: Publish both to Gihub Packages and Maven Central
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup protoc
        uses: arduino/setup-protoc@v1.1.0
        with:
          version: 3.7.1
      - name: Build with Maven
        run: mvn -B package
      - name: Send Jar File To Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/proto.jar
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Pgithub
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
      - name: Publish to Apache Maven Central
        run: mvn deploy -Pmaven
        env:
          MAVEN_USERNAME: tcpayDev
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}